// Code generated by protoc-gen-go.
// source: baidu_rpc_meta.proto
// DO NOT EDIT!

/*
Package brpc is a generated protocol buffer package.

It is generated from these files:
	baidu_rpc_meta.proto

It has these top-level messages:
	RpcMeta
	RpcRequestMeta
	RpcResponseMeta
*/
package baidu_std

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type RpcMeta struct {
	Request          *RpcRequestMeta  `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
	Response         *RpcResponseMeta `protobuf:"bytes,2,opt,name=response" json:"response,omitempty"`
	CompressType     *int32           `protobuf:"varint,3,opt,name=compress_type" json:"compress_type,omitempty"`
	CorrelationId    *int64           `protobuf:"varint,4,opt,name=correlation_id" json:"correlation_id,omitempty"`
	AttachmentSize   *int32           `protobuf:"varint,5,opt,name=attachment_size" json:"attachment_size,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *RpcMeta) Reset()                    { *m = RpcMeta{} }
func (m *RpcMeta) String() string            { return proto.CompactTextString(m) }
func (*RpcMeta) ProtoMessage()               {}
func (*RpcMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RpcMeta) GetRequest() *RpcRequestMeta {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *RpcMeta) GetResponse() *RpcResponseMeta {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *RpcMeta) GetCompressType() int32 {
	if m != nil && m.CompressType != nil {
		return *m.CompressType
	}
	return 0
}

func (m *RpcMeta) GetCorrelationId() int64 {
	if m != nil && m.CorrelationId != nil {
		return *m.CorrelationId
	}
	return 0
}

func (m *RpcMeta) GetAttachmentSize() int32 {
	if m != nil && m.AttachmentSize != nil {
		return *m.AttachmentSize
	}
	return 0
}

type RpcRequestMeta struct {
	ServiceName      *string `protobuf:"bytes,1,req,name=service_name" json:"service_name,omitempty"`
	MethodName       *string `protobuf:"bytes,2,req,name=method_name" json:"method_name,omitempty"`
	LogId            *int64  `protobuf:"varint,3,opt,name=log_id" json:"log_id,omitempty"`
	TraceId          *int64  `protobuf:"varint,4,opt,name=trace_id" json:"trace_id,omitempty"`
	SpanId           *int64  `protobuf:"varint,5,opt,name=span_id" json:"span_id,omitempty"`
	ParentSpanId     *int64  `protobuf:"varint,6,opt,name=parent_span_id" json:"parent_span_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RpcRequestMeta) Reset()                    { *m = RpcRequestMeta{} }
func (m *RpcRequestMeta) String() string            { return proto.CompactTextString(m) }
func (*RpcRequestMeta) ProtoMessage()               {}
func (*RpcRequestMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RpcRequestMeta) GetServiceName() string {
	if m != nil && m.ServiceName != nil {
		return *m.ServiceName
	}
	return ""
}

func (m *RpcRequestMeta) GetMethodName() string {
	if m != nil && m.MethodName != nil {
		return *m.MethodName
	}
	return ""
}

func (m *RpcRequestMeta) GetLogId() int64 {
	if m != nil && m.LogId != nil {
		return *m.LogId
	}
	return 0
}

func (m *RpcRequestMeta) GetTraceId() int64 {
	if m != nil && m.TraceId != nil {
		return *m.TraceId
	}
	return 0
}

func (m *RpcRequestMeta) GetSpanId() int64 {
	if m != nil && m.SpanId != nil {
		return *m.SpanId
	}
	return 0
}

func (m *RpcRequestMeta) GetParentSpanId() int64 {
	if m != nil && m.ParentSpanId != nil {
		return *m.ParentSpanId
	}
	return 0
}

type RpcResponseMeta struct {
	ErrorCode        *int32  `protobuf:"varint,1,opt,name=error_code" json:"error_code,omitempty"`
	ErrorText        *string `protobuf:"bytes,2,opt,name=error_text" json:"error_text,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RpcResponseMeta) Reset()                    { *m = RpcResponseMeta{} }
func (m *RpcResponseMeta) String() string            { return proto.CompactTextString(m) }
func (*RpcResponseMeta) ProtoMessage()               {}
func (*RpcResponseMeta) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RpcResponseMeta) GetErrorCode() int32 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *RpcResponseMeta) GetErrorText() string {
	if m != nil && m.ErrorText != nil {
		return *m.ErrorText
	}
	return ""
}

func init() {
	proto.RegisterType((*RpcMeta)(nil), "brpc.RpcMeta")
	proto.RegisterType((*RpcRequestMeta)(nil), "brpc.RpcRequestMeta")
	proto.RegisterType((*RpcResponseMeta)(nil), "brpc.RpcResponseMeta")
}

var fileDescriptor0 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0x95, 0xa4, 0x69, 0xda, 0x29, 0x24, 0xc8, 0xa4, 0x90, 0x25, 0x8a, 0x84, 0xe8, 0x2a,
	0x0b, 0x76, 0x1c, 0x82, 0x4d, 0x2f, 0x60, 0xb9, 0xce, 0x88, 0x46, 0x6a, 0x62, 0x33, 0x9e, 0x22,
	0xe0, 0x00, 0xdc, 0x83, 0x9b, 0xe2, 0x38, 0x08, 0xaa, 0x6e, 0xdf, 0xbc, 0xd1, 0xff, 0x33, 0x50,
	0xee, 0x54, 0xd7, 0x1e, 0x25, 0x59, 0x2d, 0x7b, 0x64, 0xd5, 0x58, 0x32, 0x6c, 0xc4, 0x6c, 0xe7,
	0x41, 0xfd, 0x1d, 0x41, 0xb6, 0xb5, 0xfa, 0xd9, 0x73, 0x71, 0x0f, 0x19, 0xe1, 0xeb, 0x11, 0x1d,
	0x57, 0xd1, 0x5d, 0xb4, 0x59, 0x3d, 0x96, 0xcd, 0xe8, 0x34, 0x7e, 0xbe, 0x9d, 0x78, 0xd0, 0x1e,
	0x60, 0x41, 0xe8, 0xac, 0x19, 0x1c, 0x56, 0x71, 0xf0, 0xd6, 0x27, 0xde, 0x34, 0x08, 0xe2, 0x1a,
	0x2e, 0xb5, 0xe9, 0xad, 0x97, 0x9d, 0xe4, 0x0f, 0x8b, 0x55, 0xe2, 0xed, 0x54, 0xdc, 0x40, 0xae,
	0x0d, 0x11, 0x1e, 0x14, 0x77, 0x66, 0x90, 0x5d, 0x5b, 0xcd, 0x3c, 0x4f, 0xc4, 0x2d, 0x14, 0x8a,
	0x59, 0xe9, 0x7d, 0x8f, 0x03, 0x4b, 0xd7, 0x7d, 0x62, 0x95, 0x8e, 0x0b, 0xf5, 0x57, 0x04, 0xf9,
	0x59, 0x87, 0x12, 0x2e, 0x1c, 0xd2, 0x5b, 0xa7, 0x51, 0x0e, 0xaa, 0x47, 0xdf, 0x37, 0xde, 0x2c,
	0xc5, 0x35, 0xac, 0xfc, 0x81, 0x7b, 0xd3, 0x4e, 0x30, 0x0e, 0x30, 0x87, 0xf9, 0xc1, 0xbc, 0x8c,
	0x31, 0x49, 0x88, 0xb9, 0x82, 0x05, 0x93, 0xf2, 0x8b, 0x7f, 0xc1, 0x05, 0x64, 0xce, 0xaa, 0xd0,
	0x24, 0x0d, 0xc0, 0x37, 0xb4, 0x8a, 0x42, 0x8b, 0x5f, 0x3e, 0x1f, 0x79, 0xfd, 0x04, 0xc5, 0xf9,
	0x8d, 0x02, 0x00, 0x89, 0x0c, 0x49, 0x6d, 0x5a, 0x0c, 0x6f, 0x4b, 0xff, 0x19, 0xe3, 0x3b, 0x87,
	0x17, 0x2d, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x4d, 0xd2, 0xda, 0x98, 0x84, 0x01, 0x00, 0x00,
}
